=== Slackboot20/Parcial-II-bases-de-datos-II/punto4/empleados.dtd
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre, departamento, salario) >
<!ATTLIST empleado id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT salario (#PCDATA)>

=== Slackboot20/Parcial-II-bases-de-datos-II/punto4/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados SYSTEM "empleados.dtd">
<empleados>
    <empleado id="e1">
        <nombre>Nicolas Llamas</nombre>
        <departamento>Desarrollo</departamento>
        <salario>3000000</salario>
    </empleado>
    <empleado id="e2">
        <nombre>Emili Carvajal</nombre>
        <departamento>Marketing</departamento>
        <salario>2300000</salario>
    </empleado>
    <empleado id="e3">
        <nombre>Kevin Giraldo</nombre>
        <departamento>Recursos Humanos</departamento>
        <salario>1600000</salario>
    </empleado>
</empleados>
